import shutil
from pathlib import Path
from typing import Any, Dict, List


def bootstrap_paper_project(templates_root: Path, paper_project: Path) -> None:
    if (paper_project / "main.tex").exists():
        return
    shutil.copytree(templates_root, paper_project, dirs_exist_ok=True)
    (paper_project / "tables").mkdir(parents=True, exist_ok=True)
    (paper_project / "figures").mkdir(parents=True, exist_ok=True)


def _fmt(v: Any) -> str:
    return "N/A" if v is None else str(v)


def write_experiments_section(path: Path, experiments: List[Dict[str, Any]]) -> None:
    lines = [
        "\\section{Experiments}",
        f"Discovered experiments: {len(experiments)}.",
        "\\begin{tabular}{lll}",
        "\\toprule",
        "Experiment & Metric & Best value \\\\",
        "\\midrule",
    ]
    for exp in experiments:
        selected = exp.get("selected_best", {})
        metric = selected.get("metric", "N/A") if isinstance(selected, dict) else "N/A"
        value = selected.get("value") if isinstance(selected, dict) else None
        lines.append(f"{exp['rel_path']} & {_fmt(metric)} & {_fmt(value)} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_method_section(path: Path, method_spec: Dict[str, Any]) -> None:
    name = method_spec.get("method_name", "N/A")
    backbone = method_spec.get("backbone", "N/A")
    text = (
        "\\section{Method}\n"
        "This section is a placeholder generated by cv-paper-agent.\n"
        f"Method name: {name}.\\\\\n"
        f"Backbone: {backbone}.\n"
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
