FROM python:3.8-slim
LABEL authors="HuPBA-STCE"
RUN apt-get update && apt-get install --no-install-recommends -y \
    gcc git zip curl htop libgl1-mesa-glx libglib2.0-0 libpython3-dev gnupg g++ libusb-1.0-0 libxext6 \
    libsm6 libxrender1 libfontconfig1 libice6 xvfb graphviz build-essential binutils \
    ca-certificates cmake cmake-qt-gui dbus-x11 ffmpeg gdb gfortran tar lsb-release \
    procps manpages-dev unzip wget xauth swig python3-pip python3-dev python3-numpy \
    python3-distutils python3-setuptools python3-pyqt5 python3-opencv libboost-python-dev \
    libboost-thread-dev libatlas-base-dev libavcodec-dev libavformat-dev libavutil-dev \
    libcanberra-gtk3-module libeigen3-dev libglew-dev libgl1-mesa-dev libgtk2.0-dev \
    libgtk-3-dev libjpeg-dev liblapack-dev liblapacke-dev libopenblas-dev libopencv-dev \
    libpng-dev libpostproc-dev libpq-dev libswscale-dev libtbb-dev libtesseract-dev \
    libtiff-dev libtiff5-dev libv4l-dev libx11-dev x11-xserver-utils libxine2-dev \
    libxrender-dev libxvidcore-dev libx264-dev libgtkglext1 libgtkglext1-dev \
    libvtk9-dev libdc1394-dev libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev \
    libopenexr-dev openexr pkg-config qv4l2 v4l-utils zlib1g-dev locales \
    && locale-gen en_US.UTF-8 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Establecer variables de entorno
ENV QT_DEBUG_PLUGINS=1
ENV DISPLAY=:0
ENV LC_ALL=en_US.UTF-8
WORKDIR /app
COPY . /app

COPY ./requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /app
RUN pip install --no-cache-dir -e .


WORKDIR /app/tracker

CMD ["/bin/bash", "-c", "python track_recognize.py"]