# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dldetection.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x64ldetection.proto\x12\taiservice\")\n\tDlRequest\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x0e\n\x06imdata\x18\x02 \x01(\x0c\"<\n\x0e\x44lBoundingRect\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\t\n\x01w\x18\x03 \x01(\x05\x12\t\n\x01h\x18\x04 \x01(\x05\"\x1f\n\x07\x44lPoint\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\",\n\x06\x44lMask\x12\"\n\x06points\x18\x01 \x03(\x0b\x32\x12.aiservice.DlPoint\"t\n\x08\x44lResult\x12\x0f\n\x07\x63lassid\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x12\'\n\x04rect\x18\x03 \x01(\x0b\x32\x19.aiservice.DlBoundingRect\x12\x1f\n\x04mask\x18\x04 \x01(\x0b\x32\x11.aiservice.DlMask\"2\n\nDlResponse\x12$\n\x07results\x18\x01 \x03(\x0b\x32\x13.aiservice.DlResult\"4\n\x12\x44lEmbeddingRequest\x12\x0e\n\x06imdata\x18\x01 \x01(\x0c\x12\x0e\n\x06imsize\x18\x02 \x03(\x05\"%\n\x06Tensor\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x02\x12\r\n\x05shape\x18\x02 \x03(\x05\x32\x8f\x01\n\tAiService\x12<\n\x0b\x44lDetection\x12\x14.aiservice.DlRequest\x1a\x15.aiservice.DlResponse\"\x00\x12\x44\n\x0e\x44lEmbeddingGet\x12\x1d.aiservice.DlEmbeddingRequest\x1a\x11.aiservice.Tensor\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dldetection_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DLREQUEST']._serialized_start=32
  _globals['_DLREQUEST']._serialized_end=73
  _globals['_DLBOUNDINGRECT']._serialized_start=75
  _globals['_DLBOUNDINGRECT']._serialized_end=135
  _globals['_DLPOINT']._serialized_start=137
  _globals['_DLPOINT']._serialized_end=168
  _globals['_DLMASK']._serialized_start=170
  _globals['_DLMASK']._serialized_end=214
  _globals['_DLRESULT']._serialized_start=216
  _globals['_DLRESULT']._serialized_end=332
  _globals['_DLRESPONSE']._serialized_start=334
  _globals['_DLRESPONSE']._serialized_end=384
  _globals['_DLEMBEDDINGREQUEST']._serialized_start=386
  _globals['_DLEMBEDDINGREQUEST']._serialized_end=438
  _globals['_TENSOR']._serialized_start=440
  _globals['_TENSOR']._serialized_end=477
  _globals['_AISERVICE']._serialized_start=480
  _globals['_AISERVICE']._serialized_end=623
# @@protoc_insertion_point(module_scope)
