FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential ffmpeg git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir git+https://github.com/ultralytics/ultralytics@yolo-serve litserve

ENTRYPOINT ["/bin/sh", "-c" ,"/usr/local/bin/yolo serve"]