FROM ultralytics/ultralytics:latest-python

RUN /usr/local/bin/pip install jupyterlab
RUN mkdir /data
RUN mkdir /data/datasets && /usr/local/bin/yolo settings datasets_dir="/data/datasets"
RUN mkdir /data/weights && /usr/local/bin/yolo settings weights_dir="/data/weights"
RUN mkdir /data/runs && /usr/local/bin/yolo settings runs_dir="/data/runs"
ENTRYPOINT ["/usr/local/bin/jupyter", "lab", "--allow-root", "/ultralytics/examples/tutorial.ipynb"]