# Use the official Python 3.10 slim-buster image as the base image
FROM python:3.10-slim-buster

# Install linux packages required for the image
ENV DEBIAN_FRONTEND noninteractive
RUN apt update \
    && TZ=Etc/UTC apt install -y tzdata \
    && apt install --no-install-recommends -y git zip curl htop libgl1-mesa-glx libglib2.0-0 libpython3-dev gnupg watch vim

# Copy server contents and default settings to the container
# COPY ./server/ /app/server
# COPY ./defaults/ /tmp/ultralytics-hub/defaults

# Create log directory for the application
RUN mkdir -p /app/logs

# Install the required Python packages for the application
RUN python -m pip install --upgrade pip wheel
RUN pip install --no-cache 'coremltools>=6.0,<=6.2' ultralytics[export]  \
    --extra-index-url https://download.pytorch.org/whl/cpu

# Auto-install Ultralytics ONNX and TF export packages on first use
RUN yolo export format=edgetpu imgsz=32
RUN yolo export format=paddle imgsz=32

# Set the working directory for the application
WORKDIR /app

# Set the terminal type for the container
ENV DEBIAN_FRONTEND teletype

# Expose port 8000 for the application
#EXPOSE 8000

# Define the command to run when the container starts
#CMD gunicorn -b :8000 server:app -c ./server/gunicorn.config.py