/* x86/coreinhm gmp-mparam.h -- Compiler/machine parameter header file.

Copyright 1991, 1993, 1994, 2000-2011, 2014 Free Software Foundation, Inc.

This file is part of the GNU MP Library.

The GNU MP Library is free software; you can redistribute it and/or modify
it under the terms of either:

  * the GNU Lesser General Public License as published by the Free
    Software Foundation; either version 3 of the License, or (at your
    option) any later version.

or

  * the GNU General Public License as published by the Free Software
    Foundation; either version 2 of the License, or (at your option) any
    later version.

or both in parallel, as here.

The GNU MP Library is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received copies of the GNU General Public License and the
GNU Lesser General Public License along with the GNU MP Library.  If not,
see https://www.gnu.org/licenses/.  */

#define GMP_LIMB_BITS 32
#define GMP_LIMB_BYTES 4

/* 2667 MHz Core i7 Nehalem */
/* FFT tuning limit = 100000000 */
/* Generated by tuneup.c, 2014-03-19, gcc 4.5 */

#define MOD_1_NORM_THRESHOLD                25
#define MOD_1_UNNORM_THRESHOLD              15
#define MOD_1N_TO_MOD_1_1_THRESHOLD          8
#define MOD_1U_TO_MOD_1_1_THRESHOLD          7
#define MOD_1_1_TO_MOD_1_2_THRESHOLD        11
#define MOD_1_2_TO_MOD_1_4_THRESHOLD         0  /* never mpn_mod_1s_2p */
#define PREINV_MOD_1_TO_MOD_1_THRESHOLD      3
#define USE_PREINV_DIVREM_1                  1  /* native */
#define DIV_QR_1N_PI1_METHOD                 1
#define DIV_QR_1_NORM_THRESHOLD             18
#define DIV_QR_1_UNNORM_THRESHOLD        MP_SIZE_T_MAX  /* never */
#define DIV_QR_2_PI2_THRESHOLD           MP_SIZE_T_MAX  /* never */
#define DIVEXACT_1_THRESHOLD                 0  /* always (native) */
#define BMOD_1_TO_MOD_1_THRESHOLD           15

#define MUL_TOOM22_THRESHOLD                26
#define MUL_TOOM33_THRESHOLD                89
#define MUL_TOOM44_THRESHOLD               214
#define MUL_TOOM6H_THRESHOLD               327
#define MUL_TOOM8H_THRESHOLD               466

#define MUL_TOOM32_TO_TOOM43_THRESHOLD      97
#define MUL_TOOM32_TO_TOOM53_THRESHOLD     159
#define MUL_TOOM42_TO_TOOM53_THRESHOLD      95
#define MUL_TOOM42_TO_TOOM63_THRESHOLD     101
#define MUL_TOOM43_TO_TOOM54_THRESHOLD     142

#define SQR_BASECASE_THRESHOLD               0  /* always (native) */
#define SQR_TOOM2_THRESHOLD                 44
#define SQR_TOOM3_THRESHOLD                145
#define SQR_TOOM4_THRESHOLD                232
#define SQR_TOOM6_THRESHOLD                342
#define SQR_TOOM8_THRESHOLD                502

#define MULMID_TOOM42_THRESHOLD             78

#define MULMOD_BNM1_THRESHOLD               17
#define SQRMOD_BNM1_THRESHOLD               21

#define MUL_FFT_MODF_THRESHOLD             606  /* k = 5 */
#define MUL_FFT_TABLE3                                      \
  { {    606, 5}, {     25, 6}, {     13, 5}, {     28, 6}, \
    {     15, 5}, {     33, 6}, {     29, 7}, {     15, 6}, \
    {     33, 7}, {     17, 6}, {     36, 7}, {     19, 6}, \
    {     39, 7}, {     23, 6}, {     47, 7}, {     35, 8}, \
    {     19, 7}, {     43, 8}, {     23, 7}, {     49, 8}, \
    {     31, 7}, {     63, 8}, {     43, 9}, {     23, 8}, \
    {     51, 9}, {     31, 8}, {     67, 9}, {     39, 8}, \
    {     79, 9}, {     47, 8}, {     95, 9}, {     55,10}, \
    {     31, 9}, {     79,10}, {     47, 9}, {     95,11}, \
    {     31,10}, {     63, 9}, {    135,10}, {     79, 9}, \
    {    159,10}, {     95, 9}, {    191,10}, {    111,11}, \
    {     63,10}, {    159,11}, {     95,10}, {    191,12}, \
    {     63,11}, {    127,10}, {    255, 9}, {    511,10}, \
    {    271, 9}, {    543,11}, {    159,10}, {    319, 9}, \
    {    639,10}, {    335,11}, {    191,10}, {    383, 9}, \
    {    767,10}, {    399,12}, {    127,11}, {    255,10}, \
    {    511, 9}, {   1023,10}, {    543,11}, {    287,10}, \
    {    607,11}, {    319,10}, {    639,12}, {    191,11}, \
    {    383,10}, {    767,13}, {    127,12}, {    255,11}, \
    {    511,10}, {   1023,11}, {    543,10}, {   1087,11}, \
    {    607,12}, {    319,11}, {    671,10}, {   1343,11}, \
    {    735,12}, {    383,11}, {    799,10}, {   1599,11}, \
    {    863,10}, {   1727,12}, {    447,11}, {    927,10}, \
    {   1855,11}, {    991,13}, {    255,12}, {    511,11}, \
    {   1119,12}, {    575,11}, {   1215,10}, {   2431,12}, \
    {    639,11}, {   1343,12}, {    703,11}, {   1471,13}, \
    {    383,12}, {    767,11}, {   1599,12}, {    831,11}, \
    {   1727,12}, {    895,11}, {   1855,12}, {    959,14}, \
    {    255,13}, {    511,12}, {   1023,11}, {   2111,12}, \
    {   1087,11}, {   2239,10}, {   4479,12}, {   1215,11}, \
    {   2431,13}, {    639,12}, {   1471,13}, {    767,12}, \
    {   1727,11}, {   3455,13}, {    895,12}, {   1983,11}, \
    {   3967,14}, {    511,13}, {   1023,12}, {   2239,11}, \
    {   4479,13}, {   1151,12}, {   2495,11}, {   4991,13}, \
    {   1279,12}, {   2623,13}, {   1407,12}, {   2943,14}, \
    {    767,13}, {   1535,12}, {   3071,13}, {   1663,12}, \
    {   3455,13}, {   1919,12}, {   3967,15}, {    511,14}, \
    {   1023,13}, {   2175,12}, {   4479,13}, {   2431,12}, \
    {   4991,14}, {   1279,13}, {   2687,12}, {   5503,13}, \
    {   2943,12}, {   6015,14}, {   1535,13}, {   3455,14}, \
    {   1791,13}, {   3967,12}, {   7935,15}, {   1023,14}, \
    {   2047,13}, {   4479,14}, {   2303,13}, {   4991,12}, \
    {   9983,14}, {   2559,13}, {   5503,14}, {   2815,13}, \
    {   6015,15}, {   1535,14}, {   3839,13}, {   7935,16}, \
    {   1023,15}, {   2047,14}, {   4095,13}, {   8191,12}, \
    {  16383,11}, {  32767,10}, {  65535, 9}, { 131071, 8}, \
    {    256, 9}, {    512,10}, {   1024,11}, {   2048,12}, \
    {   4096,13}, {   8192,14}, {  16384,15}, {  32768,16} }
#define MUL_FFT_TABLE3_SIZE 192
#define MUL_FFT_THRESHOLD                 6784

#define SQR_FFT_MODF_THRESHOLD             555  /* k = 5 */
#define SQR_FFT_TABLE3                                      \
  { {    555, 5}, {     28, 6}, {     15, 5}, {     31, 6}, \
    {     16, 5}, {     33, 6}, {     29, 7}, {     15, 6}, \
    {     32, 7}, {     17, 6}, {     35, 7}, {     19, 6}, \
    {     39, 7}, {     29, 8}, {     15, 7}, {     35, 8}, \
    {     19, 7}, {     41, 8}, {     23, 7}, {     49, 8}, \
    {     27, 7}, {     55, 8}, {     31, 7}, {     63, 8}, \
    {     43, 9}, {     23, 8}, {     55, 9}, {     31, 8}, \
    {     67, 9}, {     39, 8}, {     79, 9}, {     47, 8}, \
    {     95, 9}, {     55,10}, {     31, 9}, {     79,10}, \
    {     47, 9}, {     95,11}, {     31,10}, {     63, 9}, \
    {    135,10}, {     79, 9}, {    159,10}, {     95,11}, \
    {     63,10}, {    143, 9}, {    287,10}, {    159,11}, \
    {     95,12}, {     63,11}, {    127,10}, {    255, 9}, \
    {    511, 8}, {   1023,10}, {    271, 9}, {    543,10}, \
    {    287,11}, {    159,10}, {    319, 9}, {    639,10}, \
    {    335, 9}, {    671,10}, {    351,11}, {    191,10}, \
    {    383, 9}, {    767,10}, {    399, 9}, {    799,10}, \
    {    415,12}, {    127,11}, {    255,10}, {    511, 9}, \
    {   1023,10}, {    543,11}, {    287,10}, {    607,11}, \
    {    319,10}, {    671,11}, {    351,12}, {    191,11}, \
    {    383,10}, {    799,11}, {    415,13}, {    127,12}, \
    {    255,11}, {    511,10}, {   1023,11}, {    543,10}, \
    {   1087,11}, {    607,12}, {    319,11}, {    671,10}, \
    {   1343,11}, {    735,10}, {   1471,12}, {    383,11}, \
    {    799,10}, {   1599,11}, {    863,10}, {   1727,12}, \
    {    447,11}, {    991,10}, {   1983,13}, {    255,12}, \
    {    511,11}, {   1023,10}, {   2047,11}, {   1087,12}, \
    {    575,11}, {   1215,10}, {   2431,12}, {    639,11}, \
    {   1343,12}, {    703,11}, {   1471,13}, {    383,12}, \
    {    767,11}, {   1599,12}, {    831,11}, {   1727,10}, \
    {   3455,12}, {    895,11}, {   1791,12}, {    959,11}, \
    {   1983,14}, {    255,13}, {    511,12}, {   1023,11}, \
    {   2111,12}, {   1087,11}, {   2239,10}, {   4479,12}, \
    {   1215,11}, {   2431,13}, {    639,12}, {   1471,11}, \
    {   2943,13}, {    767,12}, {   1727,11}, {   3455,13}, \
    {    895,12}, {   1983,11}, {   3967,14}, {    511,13}, \
    {   1023,12}, {   2239,11}, {   4479,13}, {   1151,12}, \
    {   2495,13}, {   1279,12}, {   2623,13}, {   1407,12}, \
    {   2943,14}, {    767,13}, {   1663,12}, {   3455,13}, \
    {   1919,12}, {   3967,15}, {    511,14}, {   1023,13}, \
    {   2175,12}, {   4479,13}, {   2431,12}, {   4863,14}, \
    {   1279,13}, {   2943,12}, {   5887,14}, {   1535,13}, \
    {   3455,14}, {   1791,13}, {   3967,12}, {   7935,15}, \
    {   1023,14}, {   2047,13}, {   4479,14}, {   2303,13}, \
    {   4991,12}, {   9983,14}, {   2815,13}, {   5887,15}, \
    {   1535,14}, {   3327,13}, {   6655,14}, {   3839,13}, \
    {   7935,16}, {   1023,15}, {   2047,14}, {   4095,13}, \
    {   8191,12}, {  16383,11}, {  32767,10}, {  65535, 9}, \
    { 131071, 8}, {    256, 9}, {    512,10}, {   1024,11}, \
    {   2048,12}, {   4096,13}, {   8192,14}, {  16384,15}, \
    {  32768,16} }
#define SQR_FFT_TABLE3_SIZE 201
#define SQR_FFT_THRESHOLD                 5312

#define MULLO_BASECASE_THRESHOLD             0  /* always */
#define MULLO_DC_THRESHOLD                  38
#define MULLO_MUL_N_THRESHOLD            13463

#define DC_DIV_QR_THRESHOLD                 22
#define DC_DIVAPPR_Q_THRESHOLD              43
#define DC_BDIV_QR_THRESHOLD                78
#define DC_BDIV_Q_THRESHOLD                157

#define INV_MULMOD_BNM1_THRESHOLD           50
#define INV_NEWTON_THRESHOLD                15
#define INV_APPR_THRESHOLD                  18

#define BINV_NEWTON_THRESHOLD              351
#define REDC_1_TO_REDC_N_THRESHOLD          84

#define MU_DIV_QR_THRESHOLD                889
#define MU_DIVAPPR_Q_THRESHOLD             483
#define MUPI_DIV_QR_THRESHOLD                0  /* always */
#define MU_BDIV_QR_THRESHOLD              1589
#define MU_BDIV_Q_THRESHOLD               1787

#define POWM_SEC_TABLE  2,25,95,473,1357

#define MATRIX22_STRASSEN_THRESHOLD         20
#define HGCD_THRESHOLD                      52
#define HGCD_APPR_THRESHOLD                 51
#define HGCD_REDUCE_THRESHOLD             3524
#define GCD_DC_THRESHOLD                   213
#define GCDEXT_DC_THRESHOLD                249
#define JACOBI_BASE_METHOD                   4

#define GET_STR_DC_THRESHOLD                13
#define GET_STR_PRECOMPUTE_THRESHOLD        24
#define SET_STR_DC_THRESHOLD               145
#define SET_STR_PRECOMPUTE_THRESHOLD       545

#define FAC_DSC_THRESHOLD                   91
#define FAC_ODD_THRESHOLD                   29
