# Ultralytics 🚀 - AGPL-3.0 License https://ultralytics.com/license
# Ultralytics Actions https://github.com/ultralytics/actions
# This workflow automatically formats code and documentation in PRs to official Ultralytics standards

name: Ultralytics Actions

on:
  issues:
    types: [opened, edited]
  discussion:
    types: [created]
  pull_request:
    branches: [main]
    types: [opened, closed, synchronize, review_requested]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: namas191297/ultralytics
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Run Ultralytics Formatting
        uses: ultralytics/actions@main
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          labels: true # autolabel issues and PRs
          python: true # format Python code and docstrings
          prettier: true # format YAML, JSON, Markdown and CSS
          spelling: true # check spelling
          links: false # check broken links
          summary: false # Disable GPT summary to avoid OpenAI API key requirement
